### ISSUE TITLE
Refactor Auth for Rutorrent

### ISSUE THREAD

**Issue by JigSawFr** [Cloudbox/Cloudbox#352]
Hello,
I think it could be better to use htpasswd directory of ngin-proxy to set default auth of rutorrent instead of setting it in ruttorent container config.
Because if you want to get ride of it, each time container is re-created / updated, this setting is re-applied.

I think we could edit rutorrent role to add task:

```
- name: Create htpasswd
  htpasswd:
    path: "/opt/nginx-proxy/htpasswd/{{ item }}.{{ user.domain }}"
    name: "{{ user.name }}"
    password: "{{ user.pass }}"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: 0664
  with_items:
    - rutorrent
```

No ?
In my case i use auth of Organizr, so i need to edit each time nginx config in rutorrent container config after each update
Thank you all :)
